[package]
name = "zcash-warp"
version = "1.0.0"
edition = "2021"
authors = ["Hanh <hanh425@gmail.com>"]

[dependencies]

# Halo
orchard = "0.3.0"
halo2_proofs = "0.2"
halo2_gadgets = "0.2"
thiserror = "1.0.63"
anyhow = "1.0.86"
tracing = "0.1.40"
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }
tonic = { version = "0.8", features = ["tls", "tls-roots"] }
prost = "0.11"
r2d2 = "0.8.10"
r2d2_sqlite = "0.22.0"
rusqlite = "0.29"
lazy_static = "1.5"
parking_lot = "0.12.3"
flatbuffers = "24.3.25"
tiny-bip39 = "0.8"
tiny-hderive = "0.3.0"
secp256k1 = "0.21.3"
base58check = "0.1.0"
ripemd = "0.1.1"
sha2 = "0.10.2"
rand = "0.8.4"
hex = { version = "0.4", features = ["serde"] }
group = "0.13.0"
jubjub = "0.10.0"
rayon = "1.5.1"
blake2b_simd = "1.0.0"
chacha20 = "0.9.0"
tracing-subscriber = "0.3.18"
serde_json = "1.0.124"
serde = "1.0.206"
serde-hex = "0.1.0"
bincode = "1.3.3"
rustyrepl = { version = "0.2.0", features = ["async"] }
clap = "4.5.15"
async-trait = "0.1.81"
dotenv = "0.15.0"
serde_bytes = "0.11.15"

[features]
sqlcipher = ["rusqlite/bundled-sqlcipher-vendored-openssl"]

[dependencies.zcash_client_backend]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"
features = [ "transparent-inputs" ]

[dependencies.zcash_primitives]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"
features = [ "transparent-inputs" ]

[dependencies.zcash_proofs]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[dependencies.zcash_address]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[dependencies.zcash_encoding]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[dependencies.zcash_note_encryption]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[build-dependencies]
tonic-build = "0.8"
cbindgen = "0.26.0"

#[patch."https://github.com/hhanh00/librustzcash.git"]
#zcash_primitives = { git = "https://github.com/hhanh00/librustzcash.git", rev = "4fbdd64c89703053eeaeee51750ea6f5b93a3ec9" }
#zcash_client_backend = { git = "https://github.com/hhanh00/librustzcash.git", rev = "4fbdd64c89703053eeaeee51750ea6f5b93a3ec9" }
#zcash_encoding = { git = "https://github.com/hhanh00/librustzcash.git", rev = "4fbdd64c89703053eeaeee51750ea6f5b93a3ec9" }

[patch.crates-io]
orchard = { git = "https://github.com/zcash/orchard.git", rev = "2186856809908e004c9a04b9374aa1ba5040f409" }
halo2_gadgets  = { git = "https://github.com/zcash/halo2.git", rev = "642924d614305d882cc122739c59144109f4bd3f" }
halo2_proofs = { git = "https://github.com/zcash/halo2.git", rev = "642924d614305d882cc122739c59144109f4bd3f" }
zcash_note_encryption = { git = "https://github.com/hhanh00/librustzcash.git", rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646" }
