[package]
name = "zcash-warp"
version = "1.0.0"
edition = "2021"
authors = ["Hanh <hanh425@gmail.com>"]

[dependencies]

# Halo
orchard = "0.3.0"
halo2_proofs = "0.2"
halo2_gadgets = "0.2"
thiserror = "1.0.63"
anyhow = "1.0.86"
tracing = "0.1.40"
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }
tonic = { version = "0.8", features = ["tls", "tls-roots"] }
prost = "0.11"
r2d2 = "0.8.10"
r2d2_sqlite = "0.22.0"
rusqlite = "0.29"
lazy_static = "1.5"
parking_lot = "0.12.3"
flatbuffers = "24.3.25"
tiny-bip39 = "0.8"
tiny-hderive = "0.3.0"
secp256k1 = "0.21.3"
base58check = "0.1.0"
ripemd = "0.1.1"
sha2 = "0.10.2"
rand = "0.8.4"
hex = "0.4"
group = "0.13.0"
jubjub = "0.10.0"
rayon = "1.5.1"
blake2b_simd = "1.0.0"
chacha20 = "0.9.0"
tracing-subscriber = "0.3.18"

[features]
sqlcipher = ["rusqlite/bundled-sqlcipher-vendored-openssl"]

[dependencies.zcash_params]
git = "https://github.com/hhanh00/zcash-params.git"
rev = "47133e10ac7fa6093f0fc408761f17301f54c9e4"

[dependencies.zcash_client_backend]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"
features = [ "transparent-inputs" ]

[dependencies.zcash_primitives]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"
features = [ "transparent-inputs" ]

[dependencies.zcash_proofs]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[dependencies.zcash_address]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[dependencies.zcash_encoding]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[dependencies.zcash_note_encryption]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "e2fe0b8d386fad99e00d6135c5caf3cc04045646"

[build-dependencies]
tonic-build = "0.8"
cbindgen = "0.26.0"
